In [1]:
import numpy as np

In [7]:
l = [1, 2, 3, 4]
ar = np.array(l)
print(ar)
type(ar)

[1 2 3 4]


numpy.ndarray

In [3]:
type(ar)

numpy.ndarray

In [5]:
ar1 = np.asarray(l)
print(ar1)
type(ar1)

[1 2 3 4]


numpy.ndarray

In [6]:
ar2 = np.asanyarray(l)
print(ar2)
type(ar2)

[1 2 3 4]


numpy.ndarray

In [8]:
b=  np.matrix(l)
print(b)
type(b)

[[1 2 3 4]]


numpy.matrix

In [9]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [10]:
c = a
c

array([1, 2, 3, 4])

In [12]:
c[0] = 100
print(c)
print(a)

[100   2   3   4]
[100   2   3   4]


In [13]:
d = np.copy(a)
print(d)
print(a)

[100   2   3   4]
[100   2   3   4]


In [15]:
a[1]= 400
print(d)
print(a)

[100   2   3   4]
[100 400   3   4]


In [19]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [20]:
np.fromfunction(lambda i, j : i**j, (3, 3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])