In [122]:
import numpy as np

In [123]:
l = [1, 2, 3, 4]
ar = np.array(l)
print(ar)
type(ar)

[1 2 3 4]


numpy.ndarray

In [124]:
type(ar)

numpy.ndarray

In [125]:
ar1 = np.asarray(l)
print(ar1)
type(ar1)

[1 2 3 4]


numpy.ndarray

In [126]:
ar2 = np.asanyarray(l)
print(ar2)
type(ar2)

[1 2 3 4]


numpy.ndarray

In [127]:
b=  np.matrix(l)
print(b)
type(b)

[[1 2 3 4]]


numpy.matrix

In [128]:
ba= np.asanyarray(b)
print(ba)
type(ba)

[[1 2 3 4]]


numpy.matrix

In [129]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [130]:
c = a
c

array([1, 2, 3, 4])

In [131]:
c[0] = 100
print(c)
print(a)

[100   2   3   4]
[100   2   3   4]


In [132]:
d = np.copy(a)
print(d)
print(a)

[100   2   3   4]
[100   2   3   4]


In [133]:
a[1]= 400
print(d)
print(a)

[100   2   3   4]
[100 400   3   4]


In [134]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [135]:
np.fromfunction(lambda i, j : i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [136]:
np.fromfunction(lambda i, j : i**j, (3, 3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [137]:
iterable =  (i * i for i in range(5))
print(list(iterable))

[0, 1, 4, 9, 16]


In [138]:
np.fromiter((i * i for i in range(5)), int)

array([ 0,  1,  4,  9, 16])

In [139]:
np.fromiter(iterable, int)

array([], dtype=int64)

In [140]:
np.fromstring('234 235 6456', sep= ' ')

array([ 234.,  235., 6456.])

In [141]:
np.fromstring("1234 45678",sep=" ")

array([ 1234., 45678.])

In [142]:
# Data-Types

In [143]:
np.array([1,2,3,]).ndim

1

In [144]:
np.array([[1, 2, 3], [3, 5, 7]]).ndim

2

In [145]:
np.array([[1, 2, 3], [3, 5, 7]]).size

6

In [146]:
np.array([1,2,3,]).size

3

In [147]:
np.array([[1, 2, 3], [3, 5, 7]]).shape

(2, 3)

In [148]:
np.array([1,2,3]).shape

(3,)

In [149]:
np.array([[1, 2, 3], [3, 5, 7]]).dtype

dtype('int64')

In [150]:
ar22 = np.array([(1.4, 25, 45), (23, 45, 66)])
ar22

array([[ 1.4, 25. , 45. ],
       [23. , 45. , 66. ]])

In [151]:
ar22.dtype

dtype('float64')

In [152]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [153]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [154]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [155]:
np.arange(2.3, 5.6, .1)

array([2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])

In [156]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [157]:
np.linspace(0, 100, 21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [158]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [159]:
np.zeros((3,4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [160]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [161]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [162]:
np.ones((2, 3, 2, 3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [163]:
on = np.ones((2,3))
on

array([[1., 1., 1.],
       [1., 1., 1.]])

In [164]:
on * 4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [165]:
on + 4

array([[5., 5., 5.],
       [5., 5., 5.]])

In [166]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [167]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [168]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [169]:
np.logspace(2, 5, 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [170]:
np.logspace(2, 5, 10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [171]:
np.random.randn(3, 4)

array([[-0.37100997,  1.26965909,  1.00387001,  0.12954776],
       [ 1.28968708,  0.16652051,  0.24125922,  0.496831  ],
       [ 0.56470818,  0.84773658,  1.68946857,  0.38661852]])

In [172]:
arr = np.random.randn(3, 4)

In [173]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0  0.581887 -0.077139  0.801461 -0.159334
1  0.629978 -1.715326 -0.453414  0.317397
2  0.914798 -1.977402  0.385206  0.071557

In [174]:
np.random.rand(3,4)

array([[0.87253483, 0.06956486, 0.91363133, 0.00560399],
       [0.80569567, 0.60702762, 0.97207573, 0.35916562],
       [0.13799391, 0.8477128 , 0.57282494, 0.70797573]])

In [175]:
np.random.randint(1,100, (3,4))

array([[56, 83, 38, 81],
       [21, 72, 23, 38],
       [97, 22, 21, 75]])

In [176]:
pd.DataFrame(np.random.randint(1, 100, (20, 20))).to_csv('test.csv')

In [177]:
pd.DataFrame(np.random.randint(1, 100, (20, 20)))

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  \
0   75  79  65  82  66  28  93  58  81  22   1  86  63  47  17  41  50   4   
1   25  60  43  25   6  26  71  42  63  60  97   4  12   1  96  17  72   9   
2   26  93  73  62  46  89  75  24  50  33  77  96  57  13   2  89   2  51   
3    9  19  88  76  40  89  66  80  34  94   5  72  58  92  29  17  82  79   
4   65  71   2   3  84  48  30  60  89  19  48  94  32  86  45  69  73  65   
5   59  73  23  73  85  22  40   2   2  38   5   8  81  19  22  87  75  51   
6   11  76  68   7  30  38  96  13  58  55   6  93  57  98  37  61  37  97   
7   23  69  61  79  72  46  10  91  76  73  95  17  26  60  22  36  80  93   
8   20  25   5  42  30  56  49  20  82  69  12  69  73  23  24  50  40  18   
9   81  21  30  80  23  49  86  81  34   1  50  79  14  11  72  79  18  25   
10  31  79  63  55  90  73  27  43  63  60  28  42  36  70  43   5  96  88   
11  33  14  56  34  63  32   5  15  48  92  31  14  71  56  86  40   4  22   
12   1  98  50  17  61   4  22  38  65  27  96  87  12  44  22  67  98  89   
13  73  41  84  18  91  37  77  24  60  21  37  99  40  36  43  50  53  37   
14  59  52  34  36  41  73  86   5  44  50   7  41  13  57  35  48  74   9   
15  64  64  87  68  95  52  25  27  20  85  22  32  90  64  86   1  61  16   
16  66  98  29  87  25  90  26  73  71  22  61   4  12  30  52  27  86   6   
17  33  88  73  76   5  40  22  78  50  97  65  26   5  32  15  23  98  60   
18  69  95   2  12   9  50  33  94  93  52  92  85  44  16  66  69  53  20   
19  27  99  35  33  92   1  61  17  31  62  42  48  47  77  26  80  35   2   

    18  19  
0    3  67  
1   37  14  
2   66  75  
3   53  18  
4   34  59  
5   25   4  
6   17  93  
7   18  57  
8   62  88  
9   22  57  
10  32  20  
11  24  80  
12  82  23  
13  77  88  
14  24  44  
15  47   4  
16  13  51  
17  50  37  
18  81  30  
19   3  32

In [178]:
arr = np.random.randint(1,100, (3,4))
arr

array([[64, 90, 73, 31],
       [83, 66,  1, 87],
       [29, 18, 37, 20]])

In [179]:
arr.reshape(6, 2)

array([[64, 90],
       [73, 31],
       [83, 66],
       [ 1, 87],
       [29, 18],
       [37, 20]])

In [180]:
arr.reshape(2, 6)

array([[64, 90, 73, 31, 83, 66],
       [ 1, 87, 29, 18, 37, 20]])

In [181]:
arr.reshape(2, -1234)

array([[64, 90, 73, 31, 83, 66],
       [ 1, 87, 29, 18, 37, 20]])

In [182]:
arr1 = np.random.randint(1,100, (6,7))
print(arr1)

[[58  8 48 61 60 93 86]
 [ 7 76 21 38 45 55 41]
 [57 31 84 32 82 11 91]
 [14 67 87 92 38  7 13]
 [65 22 83 59 67 39 89]
 [13 82 41  4  9 11 75]]


In [183]:
arr1[2:5,-1]

array([91, 13, 89])

In [184]:
arr1[2:5,3]

array([32, 92, 59])

In [185]:
arr1[2,-1]

91

In [186]:
arr1[2][1:5]

array([31, 84, 32, 82])

In [187]:
arr2 = np.random.randint(1,100, (6,7))
arr2

array([[97, 73, 48, 87, 58, 64, 65],
       [33, 14, 84, 50, 84, 17,  3],
       [79, 19, 44, 92,  2, 13, 61],
       [56,  5, 12, 35, 80, 33, 58],
       [ 3,  1, 77, 92, 11, 72, 61],
       [50, 39,  9, 15, 39, 60,  4]])

In [188]:
arr2>50

array([[ True,  True, False,  True,  True,  True,  True],
       [False, False,  True, False,  True, False, False],
       [ True, False, False,  True, False, False,  True],
       [ True, False, False, False,  True, False,  True],
       [False, False,  True,  True, False,  True,  True],
       [False, False, False, False, False,  True, False]])

In [189]:
arr2[arr2>50]

array([97, 73, 87, 58, 64, 65, 84, 84, 79, 92, 61, 56, 80, 58, 77, 92, 72,
       61, 60])

In [190]:
arr3 = np.random.randint(1,100, (6,7))
arr3

array([[43, 52, 76, 61, 73, 83, 79],
       [44, 64, 51, 67, 18, 66, 77],
       [57, 52, 19, 48, 35, 52,  7],
       [17, 46, 36, 63, 46, 98, 44],
       [22, 34, 99, 68, 74, 65, 86],
       [70, 36, 39, 35, 89,  6, 24]])

In [191]:
arr3[2:4, 2:4]

array([[19, 48],
       [36, 63]])

In [192]:
arr3[2:4, 3:]

array([[48, 35, 52,  7],
       [63, 46, 98, 44]])

In [193]:
arr3 = np.random.randint(1,100, (6,7))
arr3

array([[42, 23, 19,  8,  7, 13, 73],
       [55, 51, 21,  3, 33, 65, 28],
       [84, 34, 33, 83, 52, 21, 53],
       [94, 89, 35, 40, 23, 49, 91],
       [91, 66, 36, 18, 56, 56, 64],
       [31, 76, 32, 30, 33,  2, 34]])

In [194]:
arr3[0][0]=1000
arr3

array([[1000,   23,   19,    8,    7,   13,   73],
       [  55,   51,   21,    3,   33,   65,   28],
       [  84,   34,   33,   83,   52,   21,   53],
       [  94,   89,   35,   40,   23,   49,   91],
       [  91,   66,   36,   18,   56,   56,   64],
       [  31,   76,   32,   30,   33,    2,   34]])

In [195]:
cal1 = np.random.randint(1,3, (3,3))
print(cal1)
cal2 = np.random.randint(1,3, (3,3))
print(cal2)
print("Addition : ")
print(cal1 + cal2)
print("Subtraction : ")
print(cal1 - cal2)
print("Division : ")
print(cal1 / cal2)
print("Multiplication : ")
print(cal1 * cal2)
print("Matrix Multiplication : ")
print(cal1 @ cal2)

[[1 1 1]
 [1 2 2]
 [2 2 1]]
[[1 1 2]
 [1 2 1]
 [1 2 1]]
Addition : 
[[2 2 3]
 [2 4 3]
 [3 4 2]]
Subtraction : 
[[ 0  0 -1]
 [ 0  0  1]
 [ 1  0  0]]
Division : 
[[1.  1.  0.5]
 [1.  1.  2. ]
 [2.  1.  1. ]]
Multiplication : 
[[1 1 2]
 [1 4 2]
 [2 4 1]]
Matrix Multiplication : 
[[3 5 4]
 [5 9 6]
 [5 8 7]]


In [196]:
# Row wise Broadcasting
b1 = np.zeros((4, 4))
print(b1)
row = np.array([1,2,3,4])
print(row)
b1 + row

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 2 3 4]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [197]:
# Column wise Broadcasting
b1 = np.zeros((4, 4))
print(b1)
row = np.array([[1,2,3,4]])
print(row)
row.T
print(row)
b1 + row

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 2 3 4]]
[[1 2 3 4]]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [198]:
a1 = np.random.randint(1,3, (3,3))
a1

array([[2, 2, 1],
       [2, 1, 2],
       [2, 1, 2]])

In [199]:
np.sqrt(a1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356]])

In [200]:
np.exp(a1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [201]:
np.log10(a1)

array([[0.30103, 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.30103]])

In [202]:
import numpy as np

In [203]:
arr = np.random.randint(1, 10, (3,4))
arr

array([[5, 5, 8, 9],
       [8, 5, 7, 9],
       [4, 3, 6, 1]])

In [204]:
arr.reshape(6, -45678)

array([[5, 5],
       [8, 9],
       [8, 5],
       [7, 9],
       [4, 3],
       [6, 1]])

In [205]:
arr.reshape(2, 6)

array([[5, 5, 8, 9, 8, 5],
       [7, 9, 4, 3, 6, 1]])

In [206]:
arr

array([[5, 5, 8, 9],
       [8, 5, 7, 9],
       [4, 3, 6, 1]])

In [207]:
np.size(arr)

12

In [208]:
arr.reshape(1,12)

array([[5, 5, 8, 9, 8, 5, 7, 9, 4, 3, 6, 1]])

In [209]:
arr.T

array([[5, 8, 4],
       [5, 5, 3],
       [8, 7, 6],
       [9, 9, 1]])

In [210]:
arr.flatten()

array([5, 5, 8, 9, 8, 5, 7, 9, 4, 3, 6, 1])

In [211]:
arr

array([[5, 5, 8, 9],
       [8, 5, 7, 9],
       [4, 3, 6, 1]])

In [212]:
arr.ndim

2

In [213]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [214]:
arr1.ndim

1

In [215]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 4, 5, 6]])

In [216]:
arr1

array([1, 2, 3, 4, 5, 6])

In [217]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [218]:
arr

array([[5, 5, 8, 9],
       [8, 5, 7, 9],
       [4, 3, 6, 1]])

In [219]:
np.squeeze(arr)

array([[5, 5, 8, 9],
       [8, 5, 7, 9],
       [4, 3, 6, 1]])

In [220]:
data = np.array([[1], [2],[3]])
data

array([[1],
       [2],
       [3]])

In [221]:
np.squeeze(data)

array([1, 2, 3])

In [222]:
arr1

array([1, 2, 3, 4, 5, 6])

In [223]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6])

In [224]:
print(arr1)
np.roll(arr1, 2)

[1 2 3 4 5 6]


array([5, 6, 1, 2, 3, 4])

In [225]:
np.diag(arr1)

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [226]:
arr

array([[5, 5, 8, 9],
       [8, 5, 7, 9],
       [4, 3, 6, 1]])

In [227]:
np.diag(arr)

array([5, 5, 6])

In [228]:
# Numpy Binary Operation

In [229]:
d1 = np.random.randint(1,7, (4,4))
print(d1)
d2 = np.random.randint(5,10, (4,4))
print(d2)

[[2 1 3 3]
 [6 6 3 2]
 [2 4 4 6]
 [3 1 6 2]]
[[9 7 5 5]
 [7 7 9 7]
 [5 7 5 5]
 [7 5 6 7]]


In [230]:
d1 + d2

array([[11,  8,  8,  8],
       [13, 13, 12,  9],
       [ 7, 11,  9, 11],
       [10,  6, 12,  9]])

In [231]:
d2 - d1

array([[ 7,  6,  2,  2],
       [ 1,  1,  6,  5],
       [ 3,  3,  1, -1],
       [ 4,  4,  0,  5]])

In [289]:
d1 * d2

array([[18,  7, 15, 15],
       [42, 42, 27, 14],
       [10, 28, 20, 30],
       [21,  5, 36, 14]])

In [233]:
d1/d2

array([[0.22222222, 0.14285714, 0.6       , 0.6       ],
       [0.85714286, 0.85714286, 0.33333333, 0.28571429],
       [0.4       , 0.57142857, 0.8       , 1.2       ],
       [0.42857143, 0.2       , 1.        , 0.28571429]])

In [234]:
d2/d1

array([[4.5       , 7.        , 1.66666667, 1.66666667],
       [1.16666667, 1.16666667, 3.        , 3.5       ],
       [2.5       , 1.75      , 1.25      , 0.83333333],
       [2.33333333, 5.        , 1.        , 3.5       ]])

In [235]:
d2%d1

array([[1, 0, 2, 2],
       [1, 1, 0, 1],
       [1, 3, 1, 5],
       [1, 0, 0, 1]])

In [236]:
d2 ** d1

array([[    81,      7,    125,    125],
       [117649, 117649,    729,     49],
       [    25,   2401,    625,  15625],
       [   343,      5,  46656,     49]])

In [237]:
d1 & d2

array([[0, 1, 1, 1],
       [6, 6, 1, 2],
       [0, 4, 4, 4],
       [3, 1, 6, 2]])

In [238]:
~d1

array([[-3, -2, -4, -4],
       [-7, -7, -4, -3],
       [-3, -5, -5, -7],
       [-4, -2, -7, -3]])

In [290]:
d1

array([[2, 1, 3, 3],
       [6, 6, 3, 2],
       [2, 4, 4, 6],
       [3, 1, 6, 2]])

In [239]:
d1 | d2

array([[11,  7,  7,  7],
       [ 7,  7, 11,  7],
       [ 7,  7,  5,  7],
       [ 7,  5,  6,  7]])

In [240]:
d1 > d2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [241]:
d1<d2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True, False,  True]])

In [242]:
# Numpy String functions

In [243]:
s1 = np.array(['VaibhaV', 'Arde'])
s1

array(['VaibhaV', 'Arde'], dtype='<U7')

In [244]:
s1.dtype

dtype('<U7')

In [245]:
np.char.upper(s1)

array(['VAIBHAV', 'ARDE'], dtype='<U7')

In [246]:
np.char.title(s1)

array(['Vaibhav', 'Arde'], dtype='<U7')

In [247]:
np.char.capitalize(s1)

array(['Vaibhav', 'Arde'], dtype='<U7')

In [248]:
# Numpy - Mathematical functions

In [249]:
num1 = np.random.randint(1,7, (3,4))
num1

array([[2, 2, 2, 5],
       [6, 5, 5, 3],
       [1, 6, 5, 1]])

In [250]:
np.sin(num1)

array([[ 0.90929743,  0.90929743,  0.90929743, -0.95892427],
       [-0.2794155 , -0.95892427, -0.95892427,  0.14112001],
       [ 0.84147098, -0.2794155 , -0.95892427,  0.84147098]])

In [251]:
np.cos(num1)

array([[-0.41614684, -0.41614684, -0.41614684,  0.28366219],
       [ 0.96017029,  0.28366219,  0.28366219, -0.9899925 ],
       [ 0.54030231,  0.96017029,  0.28366219,  0.54030231]])

In [252]:
np.tan(num1)

array([[-2.18503986, -2.18503986, -2.18503986, -3.38051501],
       [-0.29100619, -3.38051501, -3.38051501, -0.14254654],
       [ 1.55740772, -0.29100619, -3.38051501,  1.55740772]])

In [253]:
np.tanh(num1)

array([[0.96402758, 0.96402758, 0.96402758, 0.9999092 ],
       [0.99998771, 0.9999092 , 0.9999092 , 0.99505475],
       [0.76159416, 0.99998771, 0.9999092 , 0.76159416]])

In [254]:
np.log10(num1)

array([[0.30103   , 0.30103   , 0.30103   , 0.69897   ],
       [0.77815125, 0.69897   , 0.69897   , 0.47712125],
       [0.        , 0.77815125, 0.69897   , 0.        ]])

In [255]:
np.exp(num1)

array([[  7.3890561 ,   7.3890561 ,   7.3890561 , 148.4131591 ],
       [403.42879349, 148.4131591 , 148.4131591 ,  20.08553692],
       [  2.71828183, 403.42879349, 148.4131591 ,   2.71828183]])

In [256]:
np.sqrt(num1)

array([[1.41421356, 1.41421356, 1.41421356, 2.23606798],
       [2.44948974, 2.23606798, 2.23606798, 1.73205081],
       [1.        , 2.44948974, 2.23606798, 1.        ]])

In [257]:
np.power(num1,2)

array([[ 4,  4,  4, 25],
       [36, 25, 25,  9],
       [ 1, 36, 25,  1]])

In [258]:
np.mean(num1)

3.5833333333333335

In [259]:
np.median(num1)

4.0

In [260]:
np.std(arr1)

1.707825127659933

In [261]:
np.var(num1)

3.409722222222222

In [262]:
np.min(num1)

1

In [263]:
np.max(num1)

6

In [264]:
import numpy as np

In [265]:
arr= np.array([4,5,6,7,8,2,3,12,45,81,91,100])
arr

array([  4,   5,   6,   7,   8,   2,   3,  12,  45,  81,  91, 100])

In [266]:
np.sort(arr)

array([  2,   3,   4,   5,   6,   7,   8,  12,  45,  81,  91, 100])

In [267]:
np.searchsorted(arr, 37)

8

In [268]:
arr1= np.array([0,0,0,0,0,2,3,12,45,0,0,0,0,0,81,91,100])
np.count_nonzero(arr1)

7

In [269]:
np.where(arr1>30)

(array([ 8, 14, 15, 16]),)

In [270]:
arr1.byteswap()

array([                  0,                   0,                   0,
                         0,                   0,  144115188075855872,
        216172782113783808,  864691128455135232, 3242591731706757120,
                         0,                   0,                   0,
                         0,                   0, 5836665117072162816,
       6557241057451442176, 7205759403792793600])

In [271]:
np.extract(arr1>30, arr1)

array([ 45,  81,  91, 100])

In [272]:
c1= np.array([2,3,12,45,0,81,91,100])
c1

array([  2,   3,  12,  45,   0,  81,  91, 100])

In [273]:
c2 = np.copy(c1)
print(c2)

[  2   3  12  45   0  81  91 100]


In [274]:
c3= c1.view()
c3

array([  2,   3,  12,  45,   0,  81,  91, 100])

In [275]:
c1[0]=100

In [276]:
c1

array([100,   3,  12,  45,   0,  81,  91, 100])

In [277]:
c2

array([  2,   3,  12,  45,   0,  81,  91, 100])

In [278]:
c3

array([100,   3,  12,  45,   0,  81,  91, 100])

In [279]:
import numpy.matlib as nm

In [280]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [281]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [282]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [283]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [284]:
n1 = np.random.randint([[2,3],[4,5]])
n1

array([[0, 1],
       [2, 1]])

In [285]:
m1 = np.random.randint(1,9,(3,3))
m1

array([[8, 2, 8],
       [5, 8, 3],
       [1, 7, 4]])

In [286]:
m2 = np.random.randint(1,9,(3,3))
m2

array([[5, 7, 8],
       [2, 3, 7],
       [5, 8, 2]])

In [287]:
np.dot(m1,m2)

array([[ 84, 126,  94],
       [ 56,  83, 102],
       [ 39,  60,  65]])

In [288]:
m1@m2

array([[ 84, 126,  94],
       [ 56,  83, 102],
       [ 39,  60,  65]])