In [1]:
import numpy as np

In [31]:
l = [1, 2, 3, 4]
ar = np.array(l)
print(ar)
type(ar)

[1 2 3 4]


numpy.ndarray

In [32]:
type(ar)

numpy.ndarray

In [33]:
ar1 = np.asarray(l)
print(ar1)
type(ar1)

[1 2 3 4]


numpy.ndarray

In [34]:
ar2 = np.asanyarray(l)
print(ar2)
type(ar2)

[1 2 3 4]


numpy.ndarray

In [35]:
b=  np.matrix(l)
print(b)
type(b)

[[1 2 3 4]]


numpy.matrix

In [36]:
ba= np.asanyarray(b)
print(ba)
type(ba)

[[1 2 3 4]]


numpy.matrix

In [37]:
a = np.array(l)
a

array([1, 2, 3, 4])

In [38]:
c = a
c

array([1, 2, 3, 4])

In [39]:
c[0] = 100
print(c)
print(a)

[100   2   3   4]
[100   2   3   4]


In [40]:
d = np.copy(a)
print(d)
print(a)

[100   2   3   4]
[100   2   3   4]


In [41]:
a[1]= 400
print(d)
print(a)

[100   2   3   4]
[100 400   3   4]


In [42]:
np.fromfunction(lambda i, j : i==j, (3, 3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
np.fromfunction(lambda i, j : i*j, (3, 3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [44]:
np.fromfunction(lambda i, j : i**j, (3, 3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

In [47]:
iterable =  (i * i for i in range(5))
print(list(iterable))

[0, 1, 4, 9, 16]


In [52]:
np.fromiter((i * i for i in range(5)), int)

array([ 0,  1,  4,  9, 16])

In [53]:
np.fromiter(iterable, int)

array([], dtype=int64)

In [63]:
np.fromstring('234 235 6456', sep= ' ')

array([ 234.,  235., 6456.])

In [59]:
np.fromstring("1234 45678",sep=" ")

array([ 1234., 45678.])

In [ ]:
# Data-Types

In [64]:
np.array([1,2,3,]).ndim

1

In [67]:
np.array([[1, 2, 3], [3, 5, 7]]).ndim

2

In [69]:
np.array([[1, 2, 3], [3, 5, 7]]).size

6

In [70]:
np.array([1,2,3,]).size

3

In [75]:
np.array([[1, 2, 3], [3, 5, 7]]).shape

(2, 3)

In [73]:
np.array([1,2,3]).shape

(3,)

In [76]:
np.array([[1, 2, 3], [3, 5, 7]]).dtype

dtype('int64')

In [78]:
ar22 = np.array([(1.4, 25, 45), (23, 45, 66)])
ar22

array([[ 1.4, 25. , 45. ],
       [23. , 45. , 66. ]])

In [79]:
ar22.dtype

dtype('float64')

In [81]:
list(range(1, 10, 2))

[1, 3, 5, 7, 9]

In [82]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [83]:
np.arange(2.3, 5.6)

array([2.3, 3.3, 4.3, 5.3])

In [84]:
np.arange(2.3, 5.6, .1)

array([2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5])

In [85]:
np.linspace(1, 5, 10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [93]:
np.linspace(0, 100, 21)

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100.])

In [94]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [95]:
np.zeros((3,4, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [96]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [97]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [98]:
np.ones((2, 3, 2, 3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [101]:
on = np.ones((2,3))
on

array([[1., 1., 1.],
       [1., 1., 1.]])

In [102]:
on * 4

array([[4., 4., 4.],
       [4., 4., 4.]])

In [103]:
on + 4

array([[5., 5., 5.],
       [5., 5., 5.]])

In [112]:
np.empty((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [113]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [116]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [117]:
np.logspace(2, 5, 10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [119]:
np.logspace(2, 5, 10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [121]:
np.random.randn(3, 4)

array([[-0.46721798,  0.61318539,  0.72946959,  1.66950644],
       [-0.68630992, -1.09199554, -0.35213375, -1.21854182],
       [-0.83392851, -1.14020752,  0.20759628, -0.12204926]])

In [122]:
arr = np.random.randn(3, 4)

In [123]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0  0.142788 -2.199590 -0.689801  3.684347
1  0.536123  2.990223 -0.186670  0.183265
2 -0.394319  2.290040  0.185839 -1.487673

In [124]:
np.random.rand(3,4)

array([[0.81011378, 0.99161213, 0.70311296, 0.60755062],
       [0.99663458, 0.68640477, 0.3311038 , 0.23122256],
       [0.80409037, 0.21162288, 0.02874565, 0.67400489]])

In [125]:
np.random.randint(1,100, (3,4))

array([[43, 79, 74, 77],
       [80, 62,  7, 85],
       [93, 56, 83, 25]])

In [128]:
pd.DataFrame(np.random.randint(1, 100, (20, 20))).to_csv('test.csv')

In [129]:
pd.DataFrame(np.random.randint(1, 100, (20, 20)))

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  \
0    6  96  77  12  18  25  68  32   1  91  42   3  47  19  78  26  17  24   
1   52  61  21  84  56  70  85  15  38  49  58  54  47  21  64  41  12  55   
2   83  23  30  44  24  54  90  58   7  87  55  73   3  74  59  94  43  45   
3    5  73  33  39  48  52  49  35   8  20  23  43  50  22  17  12  12  39   
4   40  31  87  79  18   7  96  71  23  89  67  11  94  95   3  59  81  22   
5    5  68  99  56  10  18  34  71  24  56   3  80   4  30  35  87   2  24   
6   31  13  16  53  31  43  50  77  78  66  91  54  95  68  92  13   6  23   
7   71   8  95  79   3  83  74  25  71  73  65  24  95  76  51  42  36  62   
8   60  53  49  53  71  33  89   3  35  85  11  34  66  40  78  82  72  94   
9   94   8  47  65  61  36  70   1   6  56   6   4  54  63  88  53   9  47   
10  16  25  28  48  22  41  65  55  69  31  32  47  75  72  21  42   5  90   
11  89  81  77  43  65  36  81  18  49  79  57  30  46  90  53  42  58  86   
12   5  81  77  71  84  85  17  68   2  84  76   9  27  82  12  23  94   7   
13  68  55  13  17  19  96  48  45  26  28  26  25  85  98  33  94  29  81   
14  91  29  22  52  26  28  44  59  66  21  79   2  68  35  48  72  88  96   
15  67  51   6   9  46  67  91  55  11  63  25  11  80  24   4  96   5  94   
16  96  78   2  45  26  57  96  52  86  54  64  34   5  80  44  82  98  56   
17  28  92  27  22  29  14  30  67  73  21  80  31   2  96  43  94  66  38   
18  13  66  40  16  16  94  67  21  45  37  58  67  50  59  64  36  84  25   
19  63  53  31  42   2  57  30   9   8  37  84  59  69   2  69  64  75  98   

    18  19  
0   13  56  
1   70  59  
2   53  40  
3   59  86  
4   44  99  
5   39  57  
6   46  83  
7   14  62  
8   40  48  
9   49  98  
10   5  59  
11  51  48  
12  79  69  
13  11  13  
14  28  29  
15  47  97  
16   1  70  
17  63  72  
18   5   4  
19  53  76

In [4]:
arr = np.random.randint(1,100, (3,4))
arr

array([[22, 48,  8, 25],
       [95, 11, 34,  5],
       [37,  8, 30, 32]])

In [5]:
arr.reshape(6, 2)

array([[22, 48],
       [ 8, 25],
       [95, 11],
       [34,  5],
       [37,  8],
       [30, 32]])

In [6]:
arr.reshape(2, 6)

array([[22, 48,  8, 25, 95, 11],
       [34,  5, 37,  8, 30, 32]])

In [7]:
arr.reshape(2, -1234)

array([[22, 48,  8, 25, 95, 11],
       [34,  5, 37,  8, 30, 32]])

In [3]:
arr1 = np.random.randint(1,100, (6,7))
print(arr1)

[[88 40 61 70 78 62 50]
 [91 60 20 18  7 72 16]
 [21 52 52 90 74 26 30]
 [41  2 89 19 70 67  6]
 [48 19  1  8  5 58 47]
 [56 73 77 77 52 33 30]]


In [9]:
arr1[2:5,-1]

array([30,  6, 47])

In [10]:
arr1[2:5,3]

array([90, 19,  8])

In [11]:
arr1[2,-1]

30

In [15]:
arr1[2][1:5]

array([52, 52, 90, 74])

In [17]:
arr2 = np.random.randint(1,100, (6,7))
arr2

array([[21, 47, 75, 85, 19, 76, 86],
       [81, 96, 14, 62, 47, 70, 23],
       [13, 79, 79, 42, 47, 42, 63],
       [58, 17, 10, 52, 18, 32, 30],
       [67, 78, 33, 78, 16,  7, 80],
       [11,  6, 78, 46, 31, 33,  7]])

In [18]:
arr2>50

array([[False, False,  True,  True, False,  True,  True],
       [ True,  True, False,  True, False,  True, False],
       [False,  True,  True, False, False, False,  True],
       [ True, False, False,  True, False, False, False],
       [ True,  True, False,  True, False, False,  True],
       [False, False,  True, False, False, False, False]])

In [19]:
arr2[arr2>50]

array([75, 85, 76, 86, 81, 96, 62, 70, 79, 79, 63, 58, 52, 67, 78, 78, 80,
       78])

In [21]:
arr3 = np.random.randint(1,100, (6,7))
arr3

array([[16, 57, 75, 54, 78, 49,  5],
       [ 9, 20, 35, 63, 83, 49, 33],
       [48, 40, 10, 80, 98, 48, 32],
       [31, 95,  5, 74,  9, 44, 76],
       [48, 33, 91, 43, 45, 74, 61],
       [80, 99, 36, 78, 90, 89, 21]])

In [23]:
arr3[2:4, 2:4]

array([[10, 80],
       [ 5, 74]])

In [24]:
arr3[2:4, 3:]

array([[80, 98, 48, 32],
       [74,  9, 44, 76]])

In [25]:
arr3 = np.random.randint(1,100, (6,7))
arr3

array([[19, 87, 61, 40, 53,  6, 60],
       [33, 90, 40, 88, 20, 48, 28],
       [81, 82, 59, 86, 72, 76, 87],
       [93, 68, 34, 74, 25, 79, 32],
       [83, 32, 87, 11,  8, 73, 45],
       [ 6, 59, 80, 24, 62, 32, 52]])

In [26]:
arr3[0][0]=1000
arr3

array([[1000,   87,   61,   40,   53,    6,   60],
       [  33,   90,   40,   88,   20,   48,   28],
       [  81,   82,   59,   86,   72,   76,   87],
       [  93,   68,   34,   74,   25,   79,   32],
       [  83,   32,   87,   11,    8,   73,   45],
       [   6,   59,   80,   24,   62,   32,   52]])

In [35]:
cal1 = np.random.randint(1,3, (3,3))
print(cal1)
cal2 = np.random.randint(1,3, (3,3))
print(cal2)
print("Addition : ")
print(cal1 + cal2)
print("Subtraction : ")
print(cal1 - cal2)
print("Division : ")
print(cal1 / cal2)
print("Multiplication : ")
print(cal1 * cal2)
print("Matrix Multiplication : ")
print(cal1 @ cal2)

[[1 1 1]
 [2 1 1]
 [1 2 2]]
[[2 2 2]
 [2 2 2]
 [1 1 2]]
Addition : 
[[3 3 3]
 [4 3 3]
 [2 3 4]]
Subtraction : 
[[-1 -1 -1]
 [ 0 -1 -1]
 [ 0  1  0]]
Division : 
[[0.5 0.5 0.5]
 [1.  0.5 0.5]
 [1.  2.  1. ]]
Multiplication : 
[[2 2 2]
 [4 2 2]
 [1 2 4]]
Matrix Multiplication : 
[[ 5  5  6]
 [ 7  7  8]
 [ 8  8 10]]


In [42]:
# Row wise Broadcasting
b1 = np.zeros((4, 4))
print(b1)
row = np.array([1,2,3,4])
print(row)
b1 + row

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 2 3 4]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [43]:
# Column wise Broadcasting
b1 = np.zeros((4, 4))
print(b1)
row = np.array([[1,2,3,4]])
print(row)
row.T
print(row)
b1 + row

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 2 3 4]]
[[1 2 3 4]]


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [44]:
a1 = np.random.randint(1,3, (3,3))
a1

array([[2, 2, 1],
       [1, 2, 1],
       [1, 2, 1]])

In [45]:
np.sqrt(a1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [46]:
np.exp(a1)

array([[7.3890561 , 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])

In [47]:
np.log10(a1)

array([[0.30103, 0.30103, 0.     ],
       [0.     , 0.30103, 0.     ],
       [0.     , 0.30103, 0.     ]])